{
  "hash": "b35322037ae73e68eb91976622b9b680",
  "result": {
    "engine": "knitr",
    "markdown": "# Interactions in regression: one categorical and one numeric predictor {#sec-regression-cat-num}\n\n![](/img/badge-stats.png) ![](/img/badge-r.png)\n\n\n\nIn @sec-regression-interaction, you learned how to include and interpret interactions between two categorical predictors: we modelled mean f0 in female vs male speakers in informal vs polite attitude.\nIn this chapter, we will look at a model with an interaction between a categorical and a numeric predictor instead.\nInteractions between categorical and numeric predictors work on the same principles of interactions between two categorical predictors, but it is worth going through an example.\nWe will revisit the model of reaction times from @sec-regression-lognorm, but this time we will model RTs based on both mean phoneme-level Levenshtein distance and word type (real vs non-real).\n\n## The data\n\nAs usual, let's attach the necessary packages and read the data.\nWe filter RTs to include only values above 34 ms, as we have done in @sec-regression-lognorm.\n\n``` r\nlibrary(tidyverse)\ntheme_set(theme_light())\nlibrary(brms)\nlibrary(posterior)\nlibrary(tidybayes)\nlibrary(ggdist)\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmald_filt <- readRDS(\"data/tucker2019/mald_1_1.rds\") |> \n  filter(RT > 34)\n```\n:::\n\n\nWe want to answer the following research question:\n\n> Does the effect of Levenshtein distance on RTs differ in real and non-real words?\n\nTo address this question we will need to model an interaction between distance and word type.\nBefore we move onto modelling, let's plot the data.\n@fig-phonlev-isword shows a scatter plot with mean phoneme-level Levenshtein distance on the *x*-axis and logged reaction times on the *y*-axis.\nThe plot also includes two regression lines: one for real words (in green) and one for non-real words (in orange).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nmald_filt |> \n  ggplot(aes(PhonLev, RT_log)) +\n  geom_point(alpha = 0.05) +\n  geom_smooth(aes(colour = IsWord), method = \"lm\") +\n  scale_color_brewer(palette = \"Dark2\") +\n  labs(x = \"Levenshtein distance\", y = \"RT (ms)\")\n```\n\n::: {.cell-output-display}\n![Scatter plot of Levenshtein distance vs RTs in real and non-real words.](ch-regression-cat-num_files/figure-pdf/fig-phonlev-isword-1.pdf){#fig-phonlev-isword fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nFrom glancing at the plot, it looks like the regression line is steeper in real words relative to non-real words, although they do end up overlapping at higher Levenshtein distance, thus potentially indicating a ceiling effect of Levenshtein distance.\nIndependent of the reason behind this pattern (which statistics *per se* cannot answer), we can run a regression model to quantify differences.\n\n## One categorical and one numeric predictor (no interaction)\n\nLet's start by figuring out what the model mathematical formula looks like.\nFirst, let's build the formula without the interaction term.\n\n$$\\begin{aligned}\nRT_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot l_i + \\beta_2 \\cdot w_i\\\\\n\\end{aligned}$$\n\n- $l$ is Levenshtein distance and $w$ is the indicator variable for `IsWord`.\n  $w=0$ is `TRUE` and $w=1$ is `FALSE`.\n  (The reference level of `IsWord` is `TRUE.`)\n\n- $\\beta_0$ is the intercept, i.e. the mean logged RTs (logged because it is a log-normal model) when `PhonLev` is 0 and `IsWord` is the reference level, `TRUE`.\n\n- $\\beta_1$ is the difference in outcome (i.e. mean logged RTs) for each unit increase of `PhonLev`, while controlling for `IsWord`.\n\n- $\\beta_2$ is the difference in outcome when the word is a non-real word compared to when it is a real word, while controlling for `PhonLev`.\n\nSince there is no interaction between distance and word type, the effect of distance on RTs is estimated to be the same independent of which word type the observation comes from and vice versa, the effect of word type on RTs is estimated to be the same independent of the value of distance.\nLet's run this model so we can inspect the estimates of the regression coefficients and plot the results to see what the estimated effects look like.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw <- brm(\n  RT ~ PhonLev + IsWord,\n  family = lognormal,\n  data = mald_filt,\n  cores = 4,\n  seed = 1927,\n  file = \"cache/ch-regression-cat-num-rt_lw\"\n)\n```\n:::\n\n\nThe model has three regression coefficients, as you would expect (in the following, the 80% CrI are shown).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixef(rt_lw, probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Est.Error  Q10  Q90\nIntercept       6.58      0.02 6.55 6.61\nPhonLev         0.03      0.00 0.03 0.04\nIsWordFALSE     0.11      0.01 0.10 0.12\n```\n\n\n:::\n:::\n\n\n- The `Intercept` corresponds to the logged RTs when `PhonLev` is 0 and `IsWord` is `TRUE`.\n  At 80% probability, the logged RTs in these conditions are between 6.55 and 6.61.\n\n- According to the `PhonLev` estimate, for each unit increase of `PhonLev` the logged RTs increase by 0.03 to 0.04 (when controlling for word type) at 80% confidence.\n\n- `IsWordFalse` indicates that the logged RTs are 0.1 to 0.12 higher in non-words than in real words (when controlling for distance).\n\nThe estimated effect of `PhonLev` is the same in both real words (the reference level of `IsWord`) and in non-words.\nVice versa, the estimated effect of `IsWord` is the same independent of the value of `PhonLev`.\nWe can confirm this visually by plotting the expected values.\nFor convenience, we use `conditional_effects()`.\nThis time we use the `method` argument to tell the function to plot the linear predictor (`method = \"posterior_linpred\"`) rather than the expected values (`method = \"posterior_epred\"`).\nWe do this so that we can see the effects on the linear scale of logged RTs, rather than on the original scale (since we are using a log-normal model, which makes effects on the original scale log-linear rather than simply linear).\n\n\n::: {#fig-rt-lw-cond .cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nconditional_effects(rt_lw, \"PhonLev:IsWord\", method = \"posterior_linpred\")\nconditional_effects(rt_lw, \"IsWord:PhonLev\", method = \"posterior_linpred\")\n```\n\n::: {.cell-output-display}\n![Effect of mean phoneme-level distance in real words and non-words.](ch-regression-cat-num_files/figure-pdf/fig-rt-lw-cond-1.pdf){#fig-rt-lw-cond-1 fig-align='center'}\n:::\n\n::: {.cell-output-display}\n![Effect of word type at three values of mean distance.](ch-regression-cat-num_files/figure-pdf/fig-rt-lw-cond-2.pdf){#fig-rt-lw-cond-2 fig-align='center'}\n:::\n\nPosterior draws of the linear predictor from a model without interactions (mean and 95% CrI).\n:::\n\n\nIn @fig-rt-lw-cond-1, logged RT increase with greater mean phoneme-level Levenshtein distance in both real and non-words.\nIf you look closely, you will also notice that the two regression lines are parallel.\nIn other words, the slope of the lines is the same: this is because the model estimates a single effect of mean distance for both real and non-words.\nThere is no other way this can be, because the model does not include an interaction between word type and distance.\nConversely, if we look at @fig-rt-lw-cond-2, we can see that the effect of mean distance within real and non-words is the same in both word types.\nNote that `conditional_effects()` automatically picks \"representative\" values of the numeric predictor in this plot: by default, the representative values are the mean and mean $\\pm$ 1 SD of the observed values in the data for that predictor.\nIf you compare, within each word type, the distances between the posterior logged RTs for the three values of distance, their distances are the same in both word types.\n\nHowever, we have reasons to believe that the effects of word type and mean phoneme-level distance are not totally independent from each other.\nWhy?\nBecause this is the default assumption: from a linguistic point of view, we know that non-words behave differently from real words, so it makes sense to expect that the effect of phoneme-level distance might also be different.\nSo what we really need is a model with an interaction between the two predictors.\nNote that we only fitted a model without an interaction for pedagogical reasons, but you should not fit a model without interactions if you intend to fit one with interactions.\n\n## One categorical and one numeric predictor in interaction\n\nThe model with an interaction between phoneme-level distance and word type can be represented with the following formula:\n\n$$\\begin{aligned}\nRT_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot l_i + \\beta_2 \\cdot w_i + \\beta_3 \\cdot l_i \\cdot w_i\\\\\n\\end{aligned}$$\n\nBecause of the interaction term $\\beta_3 \\cdot l_i \\cdot w_i$, now the effect of the each predictor depends on the value of the other.\nWhen distance $l = 0$ and word type is non-word, the regression formula simplifies to $\\beta_0 + \\beta_2$ (all terms with $l$ are dropped).\nWhen distance $l \\neq 0$ and word type is non-word, then all terms are preserved and whatever value $l$ takes is plugged in: $\\beta_0 + \\beta_1 \\cdot l_i + \\beta_2 + \\beta_3 \\cdot l_i$.\n\nThe R syntax for interactions between predictors of different type is the same as with two categorical predictors: you include an interaction term by adding the two predictors separated by a colon, like `PhonLev:IsWord`.\nWe have also seen the syntactic sugar `*` which automatically includes the main coefficients and the interaction term, but for clarity we use the full syntax here.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw_int <- brm(\n  # Equivalent: RT ~ PhonLev * IsWord\n  RT ~ PhonLev + IsWord + PhonLev:IsWord,\n  family = lognormal,\n  data = mald_filt,\n  cores = 4,\n  seed = 1927,\n  file = \"cache/ch-regression-cat-num-rt_lw_int\"\n)\n```\n:::\n\n\nNow that we have included an interaction, the interpretation of the `PhonLev` and `IsWordFALSE` coefficients changes.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixef(rt_lw_int, probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Estimate Est.Error   Q10   Q90\nIntercept               6.52      0.03  6.48  6.56\nPhonLev                 0.04      0.00  0.04  0.05\nIsWordFALSE             0.23      0.04  0.18  0.29\nPhonLev:IsWordFALSE    -0.02      0.01 -0.02 -0.01\n```\n\n\n:::\n:::\n\n\n- The `Intercept` is still the logged RTs when phoneme-level distance is 0 and the word is real, but you will notice that the estimate is slightly different now.\n  This is common when including an interaction between predictors.\n  Since the effects of each predictor are allowed to differ depending on the value of the other predictor, the intercept might be affected.\n\n- Now, the `PhonLev` coefficient is the effect of `PhonLev` *when the word is real*.\n  In other words, the estimate of this coefficient applies exclusively to real words.\n  Why real words?\n  Because that's the reference level of `IsWord`.\n  According to the model, for each unit increase of phoneme-level distance in real words, logged RTs increase by 0.04 to 0.05 (at 80% probability).\n  This is a slightly larger difference than that estimated by the model without the interaction.\n\n- `IsWordFALSE` tells us the difference between non-words and real words *when phoneme-level distance is 0*.\n  Why 0?\n  Because that's the \"default\" value of a numeric predictor.\n  Non-words elicit logged RTs that are 0.18 to 0.29 longer than real words, when distance is 0.\n  This difference is much larger than the one suggested by the model without an interaction.\n\n- `PhonLev:IsWordFALSE` is the coefficient of the interaction term.\n  This coefficient tells us how the effect of `PhonLev` differs in non-words vs real words.\n  In other words, it tells us what we need to add or subtract to the phoneme-level distance effect of real words to get that effect in non-words.\n  According to the model, the effect of distance in non-words on logged RTs is between 0.01 and 0.02 units smaller than the effect in real words, at 80% confidence.\n  This is because the 80% CrI of the posterior distribution of the coefficient is \\[-0.02, -0.01\\].\n\nSo what is the effect of phoneme-level distance in non-words?\nEasy, we can compute that using the posterior draws of the `PhonLev` and `PhonLev:IsWordFALSE` coefficients.\nWe simply sum them to obtain the effect of mean distance on logged RTs when the word is a non-word.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw_int_draws <- as_draws_df(rt_lw_int) |> \n  mutate(\n    # Remember to use backticks `` with column names that have colons.\n    PhonLev_false = b_PhonLev + `b_PhonLev:IsWordFALSE`\n  )\n\nquantile2(rt_lw_int_draws$PhonLev_false, probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n0.02 0.03 \n```\n\n\n:::\n:::\n\n\nThe 80% CrI of the posterior draws of the effect of distance in non-words is between 0.02 and 0.03.\nCompare it with the effect in real words, \\[0.04, 0.05\\].\nThe slope of the regression line of the effect of phoneme-level distance on logged RTs is thus less steep in non-words than in real words.\nHow less steep is quantified by the `PhonLev:IsWordFALSE` coefficient.\nHow does all this look like?\nLet's plot the posterior draws of the linear predictor using `conditional_effects()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconditional_effects(rt_lw_int, \"PhonLev:IsWord\", method = \"posterior_linpred\")\n```\n\n::: {.cell-output-display}\n![Posterior draws of the linear predictor from a model with an interaction (mean and 95% CrI).](ch-regression-cat-num_files/figure-pdf/fig-rt-lw-int-cond-1.pdf){#fig-rt-lw-int-cond fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n@fig-rt-lw-int-cond shows the regression lines for real and non-words.\nThe line is steeper in real words than in non-words.\nIn other words, for each unit increase of phoneme-level distance, the logged RTs increase more in real than in non-words.\nLet's plot the expected values now, but instead of using `conditional_effects()`, let's use `epred_draws()`.\nFirst, we need the grid:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nepred_grid <- expand_grid(\n  PhonLev = seq(min(mald_filt$PhonLev), max(mald_filt$PhonLev), by = 0.1),\n  IsWord = c(\"TRUE\", \"FALSE\")\n) |> \n  mutate(\n    # We convert IsWord to factor so we can specify the order of the levels.\n    IsWord = factor(IsWord, levels = c(\"TRUE\", \"FALSE\"))\n  )\n```\n:::\n\n\nNow, we can calculate the expected values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw_int_epred <- epred_draws(\n  rt_lw_int,\n  epred_grid\n)\n\nrt_lw_int_epred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 680,000 x 7\n# Groups:   PhonLev, IsWord, .row [170]\n   PhonLev IsWord  .row .chain .iteration .draw .epred\n     <dbl> <fct>  <int>  <int>      <int> <int>  <dbl>\n 1    5.57 TRUE       1     NA         NA     1   893.\n 2    5.57 TRUE       1     NA         NA     2   886.\n 3    5.57 TRUE       1     NA         NA     3   882.\n 4    5.57 TRUE       1     NA         NA     4   894.\n 5    5.57 TRUE       1     NA         NA     5   890.\n 6    5.57 TRUE       1     NA         NA     6   893.\n 7    5.57 TRUE       1     NA         NA     7   887.\n 8    5.57 TRUE       1     NA         NA     8   888.\n 9    5.57 TRUE       1     NA         NA     9   901.\n10    5.57 TRUE       1     NA         NA    10   890.\n# i 679,990 more rows\n```\n\n\n:::\n:::\n\n\nFor plotting effects of numeric predictors, we need to calculate the mean and lower and upper limits of the credible interval.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw_int_epred_cri <- rt_lw_int_epred |> \n  summarise(\n    mean = mean(.epred),\n    lower = quantile2(.epred, probs = 0.025),\n    upper = quantile2(.epred, probs = 0.975)\n  )\n```\n:::\n\n\nFinally, we can plot the expected values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw_int_epred_cri |> \n  ggplot(aes(PhonLev, mean)) +\n  geom_ribbon(aes(ymin = lower, ymax = upper, fill = IsWord), alpha = 0.2) +\n  geom_line(aes(colour = IsWord), linewidth = 1) +\n  scale_fill_brewer(palette = \"Dark2\") +\n  scale_colour_brewer(palette = \"Dark2\") +\n  labs(x = \"Phoneme-level distance\", y = \"Expected RTs (ms)\", colour = \"Real word?\", fill = \"Real word?\")\n```\n\n::: {.cell-output-display}\n![Expected values of RT from a model with a phoneme-level distance/word type interaction.](ch-regression-cat-num_files/figure-pdf/fig-rt-lw-int-1.pdf){#fig-rt-lw-int fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n::: callout-warning\n### Exercise 1\n\nReproduce @fig-rt-lw-int-cond using `linpred_draws()` to calculate the posterior draws of the linear predictor and then plot them with ggplot2 (like we did now with the expected values).\n:::\n\n## Calculating posterior draws at specific predictor values\n\nWith categorical/numeric interactions, it is often useful to calculate and report differences (aka comparisons) between the levels of the categorical predictor at different values of the numeric predictor.\nThere isn't a specific recipe to follow when it comes to calculating specific comparisons: it depends on the research question/hypothesis.\nHere, I illustrate how to calculate specific comparisons using three values of mean phoneme-level distance based on the range of values in the data.\nWe can use 7, 10 and 12.\nFrom @fig-rt-lw-int, we should see a decreasing difference in logged RTs between non- and real words from distance 7 to 10 to 12.\n\nWe can calculate this difference using the posterior draws (and plugging in 7, 10, 12 in the regression formula) or use `linpred_draws()`.\nI will show you the former and you will do the latter as an exercise below.\nBefore we get to the code, answer the following question.\n\n::: callout-note\n## Quiz 1\n\n\n::: {.cell layout-align=\"center\"}\nWhich is the correct regression formula to get the linear predictor of non-words when phoneme-level distance is 10? \n\n* (A) $\\beta_0 + \\beta_1 \\cdot 10$  \n* (B) $\\beta_0 + \\beta_1 \\cdot 10 + \\beta_2 + \\beta_3 \\cdot 10$  \n* (C) $\\beta_0 + \\beta_1 \\cdot 10 + \\beta_3 \\cdot 10$  \n:::\n\n:::\n\nThe following code calculates the posterior draws of the linear predictor when distance is 7, 10, 12.\nThen, it gets the posterior draws of the difference between non-words and real words at those values of phoneme-level distance.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrt_lw_int_draws <- rt_lw_int_draws |> \n  mutate(\n    # Posterior draws of the linear predictor\n    rt_log_7_true = b_Intercept + b_PhonLev * 7,\n    rt_log_7_false = b_Intercept + b_PhonLev * 7 + b_IsWordFALSE + `b_PhonLev:IsWordFALSE` * 7,\n    rt_log_10_true = b_Intercept + b_PhonLev * 10,\n    rt_log_10_false = b_Intercept + b_PhonLev * 10 + b_IsWordFALSE + `b_PhonLev:IsWordFALSE` * 10,\n    rt_log_12_true = b_Intercept + b_PhonLev * 12,\n    rt_log_12_false = b_Intercept + b_PhonLev * 12 + b_IsWordFALSE + `b_PhonLev:IsWordFALSE` * 12,\n    \n    # Posterior draws of the difference\n    rt_log_7 = rt_log_7_false - rt_log_7_true,\n    rt_log_10 = rt_log_10_false - rt_log_10_true,\n    rt_log_12 = rt_log_12_false - rt_log_12_true,\n  )\n\n# Get 90% CrI of the differences\nquantile2(rt_lw_int_draws$rt_log_7, probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n0.10 0.12 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile2(rt_lw_int_draws$rt_log_10, probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n0.03 0.08 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile2(rt_lw_int_draws$rt_log_12, probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  q10   q90 \n-0.02  0.06 \n```\n\n\n:::\n:::\n\n\nThe just calculated 80% CrIs of the posterior draws indicate that, at 80% probability, the logged RTs of non-words are 0.1 to 0.12 longer than those of real words when mean phoneme-level distance is 7, 0.03 to 0.08 longer when mean distance is 10 and they are -0.02 shorter to 0.06 longer when mean distance is 12.\nIndeed, the difference between real and non-words decreases with increasing mean distance, to the point where with mean distance 12 it is even possible that logged RTs are slightly faster in non-words than in real words (note however that the CrI spans both negative and positive values, with the majority of the CrI being along positive values).\n\n::: callout-warning\n### Exercise 2\n\nCalculate the posterior draws of the linear predictor at phoneme-level distance 7, 10 and 12 for real and non-words using `linpred_draws()`.\nThen calculate the difference between real and non-words.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Hint\n\nYou should set up a prediction grid as usual, but this time you list the specific values of distance you want.\n:::\n\n## Ratio effects\n\nLet's go back to our initial research question, *Does the effect of Levenshtein distance on RTs differ in real and non-real words?* Since the model uses a log-normal family, it is more straightforward to answer the question using ratios rather than logged milliseconds (on the linear predictor scale, i.e. logged RTs) or milliseconds (on the response scale, i.e. RTs).\nAs we've done in @sec-regression-lognorm, ratios can be calculated by exponentiating the log differences.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Real words\nquantile2(exp(rt_lw_int_draws$b_PhonLev), probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n1.04 1.05 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Non-words\nquantile2(exp(rt_lw_int_draws$b_PhonLev + rt_lw_int_draws$`b_PhonLev:IsWordFALSE`), probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n1.02 1.03 \n```\n\n\n:::\n:::\n\n\nAt 80% probability, RTs increase by a factor of 1.04-1.05 for each unit increase of mean phoneme-level Levenshtein distance in real words, while in non-words they increase by a factor of 1.02-1.03.\nIn percentages, that is a 4-5% increase in real words and a 2-3% increase in non-words.\nWe can also calculate ratios for more than one unit increase: let's say for example we want the ratio between RTs when distance is 12 and when it is 7, in real and non-words.\nFirst, we need the number of units: $12-7=5$.\nSo between distance 7 and 12 there is an increase of 5 units.\nNow we can obtain the ratio of RTs at Levenshtein distance 12 to RTs at Levenshtein distance 5 by multiplying the posterior draws of the relevant coefficients by 5.\nNote that for non-words we need to multiply both `b_PhonLev` and `b_PhonLev:IsWordFalse`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Real words\nquantile2(exp(rt_lw_int_draws$b_PhonLev * 5), probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n1.21 1.27 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Non-words\nquantile2(exp(rt_lw_int_draws$b_PhonLev * 5 + rt_lw_int_draws$`b_PhonLev:IsWordFALSE` * 5), probs = c(0.1, 0.9)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n q10  q90 \n1.11 1.17 \n```\n\n\n:::\n:::\n\n\nThe RTs increase by 21-27% from distance 7 to distance 12 in real words, but only by 11-17% in non-words, at 80% confidence.\n\n## Reporting\n\n\n\nWe fitted a Bayesian regression model using the brms package [@burkner2017] in R [@rcoreteam2025].\nWe used a log-normal distribution for the outcome variable, reaction times (RTs, milliseconds).\nWe included mean phoneme-level Levenshtein distance and word type (real vs non-real word) as the regression predictors and their interaction.\nWord type was coded using the default R treatment contrasts, with real word set as the reference level.\nSee @tbl-rt-lw-int-coefs for the full regression coefficients table.\n\nAccording to the model's intercept, The 90% CrI of RTs is \\[647, 713\\] ms when phoneme-level distance is 0 ($\\beta$ = 6.52, SD = 0.03).\nFor real words, each unit increase of phoneme-level distance increases RTs by a factor of 1.04-1.05 at 90% probability ($\\beta$ = 0.04, SD = 0.004).\nWhen distance is 0, non-real words elicit RTs that are 1.18-1.25 times longer than real words ($\\beta$ = 0.23, SD = 0.04).\nThe 90% CrI of the interaction coefficient is \\[-0.03, -0.01\\] on the log scale.\nIn other words, each unit increase of phoneme-level distance in non-words increases RTs by a factor of 1.02-1.03 at 90% confidence (cf with 1.04-1.05 in real words).\nThese results suggest that the effect of phoneme-level distance differs in real and non-real words, the effect being somewhat weaker in non-real words.\n\nWhile the research question focuses on the effect of phoneme-level distance in real and non-words (*Does the effect of Levenshtein distance on RTs differ in real and non-real words?*), we can approach the results from the point of view of comparing the RTs of real and non-words at different values of distance.\nBecause of the negative interaction coefficient, the difference in RTs between real and non-words is larger at lower phoneme-level distance and, conversely, smaller at higher phoneme-level distance.\nFor illustration, at phoneme-level distance = 7, RTs for non-words are 1.10-1.13 times longer than real words; at distance = 10, they are 1.03-1.09 longer; and at distance = 12, they are 0.97 times shorter to 1.07 times longer, at 90% probability.\n\n\n::: {#tbl-rt-lw-int-coefs .cell layout-align=\"center\" tbl-cap='Regression coefficients of the Bayesian log-normal regression model of RTs. Posterior mean, SD and 95% CrIs are shown, on the log-link scale (rounded to the second decimal).'}\n\n```{.r .cell-code  code-fold=\"true\"}\nfixef(rt_lw_int) |> knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|                    | Estimate| Est.Error|  Q2.5| Q97.5|\n|:-------------------|--------:|---------:|-----:|-----:|\n|Intercept           |     6.52|      0.03|  6.46|  6.58|\n|PhonLev             |     0.04|      0.00|  0.03|  0.05|\n|IsWordFALSE         |     0.23|      0.04|  0.15|  0.31|\n|PhonLev:IsWordFALSE |    -0.02|      0.01| -0.03| -0.01|\n\n\n:::\n:::\n\n\n## Summary\n\n::: {.callout-note appearance=\"simple\"}\n- An interaction between a categorical and numeric predictor can be included in a model with the same syntax as a categorical/categorical interaction: `cat + num + cat:num` or equivalently `cat * num`.\n\n- The interaction coefficient indicates the adjustment to the main coefficient for each unit increase of the numeric predictor, at the other level of the categorical predictor.\n\n- Estimates for more than one unit increase of the numeric predictor can be calculated by multiply the posterior draws of both the main coefficient of the numeric predictor and the interaction coefficient by the desired value.\n\n- Categorical/numeric interactions are easily extended to categorical predictors with more than one level.\n  There will be $N - 1$ interaction terms, where $N$ is the number of levels in the categorical predictor.\n:::\n",
    "supporting": [
      "ch-regression-cat-num_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}