# Interim summary {#ch-interim-summ}

Week 6 of the QML course is "catch-up" week. There are no classes and no new content is introduced, to allow you to catch up with things if you need to and/or revise the contents of Weeks 1 to 5.

If you look back at what you knew when starting in Week 1 and what you have learned up until now, especially if you were a beginner, you should be very proud of yourself! We have covered a lot of concepts and skills in a very short period of time. You have learned about research methods, research questions and research hypotheses, the perils of the research cycle and questionable research practices, Bayesian inference, the basics of R, how to read, summarise and plot data, and how to fit and interpret simple Gaussian models, including regression models like $y \sim x$.

The contents of Weeks 1 to 5 are really the bare minimum one needs to know to be able to work towards being proficient in quantitative methods, but the road to proficiency is a long one. Weeks 7 to 10 continue the learning journey of regression models and they will provide you with background knowledge in frequentist inference, another approach to statistical inference. We will scratch the surface of regression modelling, and to really become functional you will need to learn beyond this course. There is only so much we can fit in a one-semester course and to be able to get to a point where you can confidently navigate all there is to quantitative methods will take years. This is no different from studying linguistics: you don't just do one semester-long course in linguistics and then you can write a full dissertation.

Hopefully you enjoyed the learning process so far and you are looking forward to the second part!
