{
  "hash": "93553d02cbf1e3a072a5dba94acb9e4d",
  "result": {
    "engine": "knitr",
    "markdown": "# Regression models with brms {#sec-regression}\n\n![](/img/badge-r.png)\n\n\n\nIn @sec-reg-intro you were introduced to regression models.\nRegression is a statistical model based on the equation of a straight line, with added error.\n\n$$y = \\beta_0 + \\beta_1 x + \\epsilon$$\n\n$\\beta_0$ is the regression line's intercept and $\\beta_1$ is the slope of the line.\nWe have seen that $\\epsilon$ is assumed to be from a Gaussian distribution with mean 0 and standard deviation $\\sigma$.\nWe can re-express the model using the familiar notation $y \\sim Gaussian(\\mu, \\sigma)$.\n\n$$\\begin{aligned}\ny & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 + \\beta_1 x\\\\\n\\end{aligned}$$\n\nFrom now on, we will use the latter way of expressing regression models, because it makes it clear which distribution we assume the variable $y$ to be generated by (here, a Gaussian distribution).\nNote that in the wild, variables very rarely are generated by Gaussian distributions.\nIt is just pedagogically convenient to start with Gaussian regression models (i.e. regression models with a Gaussian distribution as the distribution of the outcome variable $y$) because the parameters of the Gaussian distribution, $\\mu$ and $\\sigma$ can be interpreted straightforwardly on the same scale as the outcome variable $y$: so for example if $y$ is in centimetres, then the mean and standard deviation are in centimetres, if $y$ is in Hz, then the mean and SD are in Hz, and so on.\nSimilarly, the regression $\\beta$ coefficients will be on the same scale as the outcome variable $y$.\nYou will be introduced later to regression models with distributions other than the Gaussian, where the regression parameters are estimated on a different scale than that of the outcome variable $y$.\n\nThe goal of the Gaussian regression model expressed in the formulae above is to estimate $\\beta_0$, $\\beta_1$ and $\\sigma$ from observed data.\nNow, since truly Gaussian data is difficult to come by, especially in linguistics, for the sake of pedagogical simplicity we will start the learning journey on fitting regression models using vowel durations, i.e. data for which a Gaussian regression is generally not appropriate.\nYou will learn in @sec-regression-lognorm a more appropriate distribution family for this type of data.\n\n## Vowel duration in Italian: the data\n\nWe will analyse the duration of vowels in Italian from @coretta2019k and how speech rate affects vowel duration.\nVowel duration doesn't need introductions, and speech rate is simply the number of syllables per second, calculated from the frame sentence the vowel was uttered in.\nAn expectation we might have is that vowels get shorter with increasing speech rate.\nYou will notice how this is a very vague hypothesis: how shorter do they get?\nIs the shortening the same across all speech rates, or does it get weaker with higher speech rates?\nOur expectation/hypothesis simply states that vowels get shorter with increasing speech rate.\nMaybe we could do better and use what we know from speech production and come up with something more precise, but this type of vague hypothesis are very common, if not standard, in linguistic research, so we will stick to it for practical and pedagogical reasons.\nRemember, however, that sound research should strive for precision.\n\nNonetheless, we will try to answer the following research question:\n\n> What is the relationship between vowel duration and speech rate?\n\nLet's load the R data file `coretta2018a/ita_egg.rda`.\nIt contains several phonetic measurements obtained from audio and electroglottographic recordings.\nYou can find the information on the data in the related entry on the QM Data website: [Electroglottographic data on Italian](https://uoelel.github.io/qml-data/data/coretta2018a/ita_egg.html).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(\"data/coretta2018a/ita_egg.rda\")\n\nita_egg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,268 x 52\n   speaker ipu    stimulus    sentence_ons sentence_off word_ons word_off v1_ons\n   <chr>   <chr>  <chr>              <dbl>        <dbl>    <dbl>    <dbl>  <dbl>\n 1 it01    ipu_1  Ripete 'po~         13.2         14.9     13.7     14.1   13.9\n 2 it01    ipu_2  Ripete 'to~         16.9         18.6     17.4     17.9   17.5\n 3 it01    ipu_3  Ripete 'pa~         20.2         21.9     20.7     21.1   20.8\n 4 it01    ipu_4  Sentivo 't~         23.5         25.1     24.0     24.4   24.1\n 5 it01    ipu_5  Sentivo 't~         26.3         27.8     26.8     27.2   26.9\n 6 it01    ipu_6  Scrivete '~         29.2         30.9     29.7     30.1   29.8\n 7 it01    ipu_7  Sentivo 'c~         32.1         33.6     32.6     33.1   32.8\n 8 it01    ipu_8  Scrivete '~         35.0         36.6     35.5     35.9   35.6\n 9 it01    ipu_9  Ha detto '~         41.9         43.5     42.3     42.7   42.4\n10 it01    ipu_10 Sentivo 'p~         47.4         48.9     47.9     48.4   48.1\n# i 3,258 more rows\n# i 44 more variables: c2_ons <dbl>, v2_ons <dbl>, voice_ons <dbl>,\n#   voice_off <dbl>, c1_rel <dbl>, c2_rel <dbl>, stimulus_id <dbl>,\n#   sentence <chr>, word <chr>, c1 <chr>, vowel <chr>, c2 <chr>,\n#   backness <chr>, height <fct>, c1_place <fct>, c2_place <fct>,\n#   v1_duration <dbl>, c2_clos_duration <dbl>, rel_voff <dbl>,\n#   sent_duration <dbl>, speech_rate <dbl>, speech_rate_c <dbl>, ...\n```\n\n\n:::\n:::\n\n\nAs usual, you first must attach the tidyverse package.\nWe also set the theme to the light theme.\n\n``` r\nlibrary(tidyverse)\ntheme_set(theme_light())\n```\n\nLet's plot vowel duration and speech rate in a scatter plot.\nThe relevant columns in the tibble are `v1_duration` and `speech_rate`.\nThe points in the plot are the individual observations (measurements) of vowels in the 19 speakers of Italian.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nita_egg |> \n  ggplot(aes(speech_rate, v1_duration)) +\n  geom_point(alpha = 0.5) +\n  labs(\n    x = \"Speech rate (syllables per second)\",\n    y = \"Vowel duration (ms)\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 15 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Scatter plot of speech rate (as number of syllables per second) and vowel duration (in milliseconds) in 19 Italian speakers.](ch-regression_files/figure-pdf/fig-vow-rate-1.pdf){#fig-vow-rate fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nYou might be wondering what is the warning about missing values.\nThis is because some observations of vowel duration (`v1_duration`) in the data are missing (i.e. they are `NA`, \"Not Available\").\nWe can drop them from the tibble using `drop_na()`.\nThis function takes column names as arguments: each row that has `NA` in any of the columns listed in the function will be dropped, so be careful when using `drop_na()` without listing columns because any `NA` value in any column with make the row be removed.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nita_egg_clean <- ita_egg |> \n  drop_na(v1_duration)\n```\n:::\n\n\nWe will use `ita_egg_clean` for the rest of the chapter.\nLet's reproduce the plot, but let's add a **regression line**.\nThis is the straight line we have been talking about, the line that is reconstructed by regression models.\nIt is sometimes useful to add the regression line to the scatter plots to show the linear relationship of the two variables in the plot.\nWe can quickly add regression lines to scatter plots with the smooth geometry: `geom_smooth(method = \"lm\")`.\nThe `method` argument lets us pick the type of method to create the \"smooth\": here, we want a regression line so we choose `lm` for linear model (remember, linear model is another term for regression model).\nUnder the hood, `geom_smooth()` fits a regression model to estimate the regression line and plots it.\nWe will fit our own regression model below, so for now the regression line is just for show.\n@fig-vow-rate-lm shows the scatter plot with the regression line.\nYou can ignore the message about the formula.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nita_egg_clean |> \n  ggplot(aes(speech_rate, v1_duration)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  labs(\n    x = \"Speech rate (syllables per second)\",\n    y = \"Vowel duration (ms)\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Relationship between speech rate (as number of syllables per second) and vowel duration (in milliseconds) in 19 Italian speakers.](ch-regression_files/figure-pdf/fig-vow-rate-lm-1.pdf){#fig-vow-rate-lm fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nBy glancing at the individual points, we can see a negative relationship between speech rate and vowel duration: vowels get shorter with greater speech rate.\nThis is reflected by the regression line too, which has a *negative* slope.\nA negative slope means that when the values on the *x*-axis increase, the values on the *y*-axis decrease.\nWhen the opposite is true, i.e. when with increasing *x*-axis values you observe increasing *y*-axis values, we say the regression line has *positive* slope.\nPositive and negative slope correspond to what some call a *direct* and *inverse* relationship.\nIn terms of the equation of the line $y = \\beta_0 + \\beta_1 x$, a *positive slope* means $\\beta_1$ is a *positive* number and, conversely, a *negative slope* means $\\beta_1$ is a *negative* number.\nWhen $\\beta_1$ is zero, then the regression line is flat and we say that the two variables are independent: changing one, does not systematically change the other.\nYou explored these features of the regression slope in @sec-reg-intro, when playing around with the [Regression Models Illustrated](https://stefanocoretta.shinyapps.io/lines/) app and when answering the quiz.\n\n::: callout-tip\n### Direct/positive and inverse/negative relationship\n\nWhen the slope $\\beta_1$ is positive, the regression line has **positive slope** and $x$ and $y$ have a **direct relationship**.\n\nWhen the slope $\\beta_1$ is negative, the regression line has **negative slope** and $x$ and $y$ have an **inverse relationship**.\n\nWhen the slope $\\beta_1$ is `0` zero, the regression line is flat and $x$ and $y$ are **independent**.\n:::\n\n@fig-vow-rate-lm looks very nice, but the plot doesn't tell us much about the estimates for $\\beta_0$ and $\\beta_1$.\nFor that, we need to actually fit the regression model.\n\n### The model\n\nLet's move on onto fitting a Gaussian regression model to vowel duration as the outcome variable and speech rate as the predictor.\nWe are assuming that vowel duration follows a Gaussian distribution (although as mentioned at the beginning of this chapter, this is not the case, but it will do for now).\nHere is the model we will fit, in mathematical notation.\n\n$$\\begin{aligned}\nvdur & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 + \\beta_1 \\cdot sr\\\\\n\\end{aligned}$$\n\nYou can read that as:\n\n- Vowel duration ($vdur$) is distributed ($\\sim$) according to a Gaussian distribution ($Gaussian(\\mu, \\sigma)$).\n\n- The mean $\\mu$ is equal to the sum of $\\beta_0$ (the intercept) and the product of $\\beta_1$ and speech rate ($\\beta_1 \\cdot sr$).\n  The formula of $\\mu$ is regression equation of the model.\n\nThe regression model estimates the parameters in the mathematical formulae: the parameters to be estimated in regression models are usually represented with Greek letters (hence why we adopted this notation for the linear equation).\nThe regression model in the formulae above has to estimate the following three parameters:\n\n- The *regression coefficients* $\\beta_0$ and $\\beta_1$.\n\n- The standard deviation of the Gaussian distribution, $\\sigma$.\n\n$\\beta_0$ and $\\beta_1$ are called the **regression coefficients** because they are coefficients of the regression equation.\nIn maths, a coefficient is simply a constant value that multiplies a **basis** in the equation, like the variable $sr$.\nIn the regression equation of the model, $\\beta_1$ is a multiplier of the variable $sr$, but what about $\\beta_0$?\nWell, it is implied that $\\beta_0$ is a multiplier of the constant basis `1`, because $\\beta_0 \\cdot 1 = \\beta_0$.\nKnowing this should now reveal the reason behind the strange formula that R uses in Gaussian models like the ones we fitted in @sec-fit-model: the `1` in the formula stands for the constant basis of the intercept, meaning that the model estimates the coefficient of the intercept, $\\beta_0$.\nGaussian models without predictors are in fact also called intercept-only regression models, because only an intercept is estimated.\nThere is no slope in the model because there is not variable $x$ to multiply the slope with.\n\nGoing back to our regression model of vowel duration and speech rate, we can rewrite the model formula to make the constant basis `1` explicit, thus:\n\n$$\\begin{aligned}\nvdur & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 \\cdot 1 + \\beta_1 \\cdot sr\\\\\n\\end{aligned}$$\n\nTo instruct R to model vowel duration as a function of the numeric predictor speech rate you simply *add* it to the `1` we have used in the right-hand side of the tilde in @sec-fit-model (i.e. `v1_duration ~ 1`): so `v1_duration ~ 1 + speech_rate`.\nThe R formula is based on the bases you multiply the coefficients with in the mathematical formula: $1$ and $sr$.\nIn regression parlance, the `1` and `sr` in the R formula are called predictors rather than bases.\nThe predictor $sr$ can take different values and it is known as a **variable predictor**, the $1$ is constant so it is called the **constant predictor**.\nThe coefficient and the basis together are known as **predictor terms**.\n$\\beta_0 \\cdot 1$ is known as the **constant (predictor) term** or the **intercept term**, while $\\beta_1 \\cdot sr$ is a **variable (predictor) term**.\nIn the R formula, you don't explicitly include the coefficients $\\beta_0$ and $\\beta_1$, just the bases.\nPut all this together and you get the `1 + speech_rate` part of the formula.\nThere is more: in R, since the $1$ is a constant, you can omit it!\nSo `v1_duration ~ 1 + speech_rate` can also be written as `v1_duration ~ speech_rate`.\nThey are equivalent.\n\nThat was probably a lot!\nBut now that we have clarified how the R formula is set up, we can proceed and fit the model.\nHere is the full code to fit a Gaussian regression model of vowel duration with brms.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(brms)\n\nvow_bm <- brm(\n  # `1 +` can be omitted.\n  v1_duration ~ 1 + speech_rate,\n  # v1_duration ~ speech rate,\n  family = gaussian,\n  data = ita_egg_clean\n)\n```\n:::\n\n\n\n\n::: callout-tip\n## Regression coefficients\n\nThe **regression coefficients** are the values from the regression line to be estimated in the model.\nIn a Gaussian regression, these are $\\beta_0$ and $\\beta_1$.\n\nThe regression coefficients multiply their **basis**, called **predictors** in regression modelling.\n$\\beta_0$, the intercept, multiplies the **constant** predictor $1$.\n$\\beta_1$ multiplies a **variable** predictor.\nThe combination of coefficient and basis/predictor is known as a **predictor term**.\n:::\n\n::: {.callout-important collapse=\"true\"}\n### Going further: The rethinking package\n\nMcElreath's textbook *Statistical Rethinking* [@mcelreath2020] comes with an R package, [rethinking](https://github.com/rmcelreath/rethinking), that lets you fit data using R formulae that resemble the mathematical formulae more closely.\nFor example, in rethinking the model formula of our model of vowel duration would look like the code below.\nThe package requires you to include all the formulae in a list.\nNote that the rethinking package does not set default priors, so we have included them below.\n\n``` r\nalist(\n  v1_duration ~ dnorm(mu, sigma),\n  mu <- b0 + b2 * speech_rate,\n  # Priors\n  a ~ dt(80, 25), \n  b ~ dt(0, 1),\n  sigma ~ dt(0, 25)\n)\n```\n\nIf you look closely at the the first two lines in the list, you should recognise the mathematical formulae of the model we have seen above.\n:::\n\n## Interpret the model summary\n\nAs we has seen in @sec-fit-model, to obtain a summary of the model, we use the `summary()` function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(vow_bm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: v1_duration ~ speech_rate \n   Data: ita_egg_clean (Number of observations: 3253) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     198.47      3.33   191.76   204.97 1.00     3681     2274\nspeech_rate   -21.73      0.62   -22.93   -20.49 1.00     3623     2421\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    21.66      0.27    21.14    22.19 1.00     3855     2615\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nLet's focus on the `Regression Coefficients` table of the summary.\nIt should now be clear why in the summary of the model in @sec-fit-model, the summaries for the mean $\\mu$ (i.e. $\\beta_0$) were in the regression coefficients table.\nThe table of the regression model we just fit has two coefficients.\nTo understand what they are, just remember the equation of the line and the model formula above, repeated here.\n\n$$\\begin{aligned}\nvdur & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 \\cdot 1 + \\beta_1 \\cdot sr\\\\\n\\end{aligned}$$\n\n- `Intercept` is $\\beta_0$: this is the mean vowel duration, **when speech rate is 0**.\n\n- `speech_rate` is $\\beta_1$: this is the change in vowel duration **for each unit increase of speech rate**.\n\nThis should make sense, if you understand the equation of a line: $y = \\beta_0 + \\beta_1 x$.\nRemember, the intercept $\\beta_0$ is the $y$ value when $x$ is 0.\nIn our regression model, $y$ is vowel duration $vdur$ and $x$ is speech rate $sr$.\nSo the `Intercept` is the mean vowel duration when speech rate is 0.\nRecall that the `Estimate` and `Est.Error` column are simply the **mean and standard deviation of the posterior probability distributions** of the estimate of `Intercept` and `speech_rate` respectively.\nIn this model we just have two coefficients instead of one.\nLooking at the 95% Credible Intervals (CrIs), we can say that based on the model and data:\n\n- The mean vowel duration, when speech rate is 0 syl/s, is between 192 and 205 ms, at 95% confidence.\n\n- We can be 95% confident that, for each unit increase of speech rate (i.e. for each increase of one syllable per second), the duration of the vowel decreases by 20.5-23 ms.\n\nTo answer our research question (what is the relationship between vowel duration and speech rate?) we can say that with increasing speech rate, vowel duration decreases.\nWe can be more precise than that and say that for each increase of one syllable per second, the vowel becomes 20.5 to 23 ms shorter, at 95% confidence (that is our 95% CrI).\nSince this is a regression model, it doesn't matter if we are comparing $vdur$ when $sr = 0$ vs when $sr = 1$, or when $sr = 6.5$ vs when $sr = 7.5$.\nThe slope coefficient $\\beta_1$ tells us what to add to $vdur$ when you increase $sr$ by one.\nFor example, assume you want to obtain from the model an estimate of mean $vdur$ when speech rate is 5.\nYou would just plug in $sr = 5$ in the formula:\n\n$$\\begin{aligned}\n\\mu & = \\beta_0 + \\beta_1 \\cdot 5\\\\\n\\end{aligned}$$\n\nSo that is the intercept $\\beta_0$ plus $\\beta_1$ times the speech rate, i.e. 5.\nThe only complication is that here $\\beta_0$ and $\\beta_1$ are full probability distributions, rather than single values like you would have in the simple case of the equation of a line.\nSince the coefficients are posterior probability distributions, any operation like addition and multiplication will lead to a posterior probability distribution, i.e. the posterior probability distribution of $\\mu$.\nYou will learn how do to these operations in the next chapter, @sec-regression-draws.\n\nFor now, let's focus on the posterior distributions of the coefficients.\nTo see what the posterior probability densities of $\\beta_0$, $\\beta_1$ and $\\sigma$ look like, you can quickly plot them with the `plot()` function, as we did in @sec-fit-model.\nThere is also another way: we can use the `mcmc_dens()` function from the [bayesplot](https://mc-stan.org/bayesplot/) package (why it's `mcmc_dens()` will become clear in @sec-regression-draws).\nBy default the function plots the posterior densities of all parameters in the model, plus other internal parameters that we usually don't care about.\nWe can conveniently specify which parameters to plot with the `pars` argument, which takes a character vector.\nThe names of the parameters for the regression coefficients are slightly different than what you see in the summary: `b_Intercept` and `b_speech_rate`.\nThese are just the names you see in the summary, with a prefixed `b_`.\nThe `b_` stands for beta coefficient, which makes sense, since these are the $\\beta_0$ and $\\beta_1$ coefficients.\n@fig-vow-bm shows the output of the `mcmc_dens()` function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(bayesplot)\n\nmcmc_dens(vow_bm, pars = c(\"b_Intercept\", \"b_speech_rate\", \"sigma\"))\n```\n\n::: {.cell-output-display}\n![Posterior density plots of a regression model fitted to vowel duration.](ch-regression_files/figure-pdf/fig-vow-bm-1.pdf){#fig-vow-bm fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nThese are the results of the regression model: the full posterior probability distributions of the three parameters $\\beta_0$, $\\beta_1$, $\\sigma$.\nThe posteriors can be described, as with any other probability distribution, by the values of their parameters.\nIt is common to use the mean and standard deviation, the parameters of the Gaussian distribution.\nThis is independent from the fact that we fitted a Gaussian distribution: posterior distributions tend to be bell-shaped, i.e.\nGaussian.\nThis is why the `Regression Coefficients` table of the summary reports mean and SD, i.e.\n`Estimate` and `Est.Err`, as mentioned earlier.\n\n## Were do the results come from?\n\nYou might we wondering where the the values in the model summary and the posterior distributions in the plots come from.\nTo understand this we need to discuss the MCMC (Markov Chain Monte Carlo) draws.\nYou have briefly encountered the MCMC draws the first time in @sec-fit-model, when you fitted your first Gaussian model, and you have seen references to them in the text returned while fitting the regression model of this chapter.\nAny result from a Bayesian regression model (like the summary and the distribution plots) are the output of operations performed on the MCMC draws.\nThe next chapter is a high-level introduction to the MCMC draws.\nIt will cover just enough for you to understand how to work with them to interrogate the model (and to realise the summaries and plots are just summaries and plots of the draws).\n\n## Summary\n\n::: {.callout-note appearance=\"simple\"}\n- Gaussian regression models have the following mathematical form:\n\n$$\\begin{aligned}\ny & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 + \\beta_1 x\\\\\n\\end{aligned}$$\n\n- A regression model estimates an intercept $\\beta_0$ and a slope $\\beta_1$ from the data ($x$ and $y$).\n\n- Regression models in brms are fit with the R formula `y ~ 1 + x`.\n  We can omit the constant/intercept term: `y ~ x`.\n\n- The intercept $\\beta_0$ is the mean $y$ when $x$ is `0` zero.\n\n- The slope $\\beta_1$ is the change in $y$ for every unit increase of $x$.\n:::\n",
    "supporting": [
      "ch-regression_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}