{
  "hash": "95427da2032ea4f4a538a9db3d3b8a55",
  "result": {
    "engine": "knitr",
    "markdown": "# Multiple predictors in regression {#sec-regression-cat-cat}\n\n![](/img/badge-stats.png) ![](/img/badge-r.png)\n\n\n\nSo far, we fitted regressions with a single predictor, like the following Gaussian model of reaction times from @sec-regression-cat using the data from @tucker2019:\n\n$$\\begin{aligned}\nRT_i & \\sim Gaussian(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot w_i\\\\\n\\end{aligned}$$\n\nThe categorical predictor $W$ (`IsWord` in the data) has two levels (`TRUE` and `FALSE`), so there is one intercept coefficient and one coefficient for the dummy variable $w_i$: $\\beta_0$ and $\\beta_1$.\nIn most context, however, you will want to investigate the effects of more than one predictor.\nRegression models can be fit with multiple predictors.\nTraditionally, regression models with a single predictor were called \"simple regression\" and models with more than one \"multiple regression\", but it doesn't make sense to have a specific name: they are all regression models.\nIn this chapter, we will discuss regression models with two categorical predictors.\n\n## Two categorical predictors\n\nTo illustrate how to fit and interpret models with two categorical predictors, we will use the `winter2012/polite.csv` data from @winter2012.\nThe data contains several acoustic measures from the speech of Korean speakers.\nThe participants of the study were asked to make a request imagining they were speaking either to a friend or to someone of higher status, thus producing speech in both an informal and polite condition, respectively.\nThis is coded in the `attitude` column of the `polite` data, which we read in the code below (after attaching the necessary packages first).\n\n``` r\nlibrary(tidyverse)\ntheme_set(theme_light())\nlibrary(brms)\nlibrary(ggdist)\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npolite <- read_csv(\"data/winter2012/polite.csv\")\npolite\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 224 x 27\n   subject gender birthplace musicstudent months_ger scenario task  attitude\n   <chr>   <chr>  <chr>      <chr>             <dbl>    <dbl> <chr> <chr>   \n 1 F1      F      seoul_area yes                  18        6 not   inf     \n 2 F1      F      seoul_area yes                  18        6 not   pol     \n 3 F1      F      seoul_area yes                  18        7 not   inf     \n 4 F1      F      seoul_area yes                  18        7 not   pol     \n 5 F1      F      seoul_area yes                  18        1 dct   pol     \n 6 F1      F      seoul_area yes                  18        1 dct   inf     \n 7 F1      F      seoul_area yes                  18        2 dct   pol     \n 8 F1      F      seoul_area yes                  18        2 dct   inf     \n 9 F1      F      seoul_area yes                  18        3 dct   pol     \n10 F1      F      seoul_area yes                  18        3 dct   inf     \n# i 214 more rows\n# i 19 more variables: total_duration <dbl>, articulation_rate <dbl>,\n#   f0mn <dbl>, f0sd <dbl>, f0range <dbl>, inmn <dbl>, insd <dbl>,\n#   inrange <dbl>, shimmer <dbl>, jitter <dbl>, HNRmn <dbl>, H1H2 <dbl>,\n#   breath_count <dbl>, filler_count <dbl>, hiss_count <dbl>,\n#   nasal_count <dbl>, sil_count <dbl>, ya_count <dbl>, yey_count <dbl>\n```\n\n\n:::\n:::\n\n\nThe `polite` data also contains information about the gender of the participant: in the data there are female and male participants.\nIn this chapter we will model the mean fundamental frequency (f0) of each utterance (`f0mn`) depending on gender and attitude to answer the following research question:\n\n> Do condition and gender affect the mean fundamental frequency (f0) of the utterance?\n\nThe data contains some missing f0 data, so we filter it out first.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npolite_filt <- polite |> \n  drop_na(f0mn)\n```\n:::\n\n\nNow let's plot mean f0 by gender and attitude.\nWe can achieve this by using a jitter plot by gender, with coloured points by attitude.\n@fig-polite-f0-gend-att shows this plot.\nHowever, the plot is not very legible because the points for informal and polite attitude are on the same vertical axis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npolite_filt |> \n  ggplot(aes(gender, f0mn, colour = attitude)) +\n  geom_jitter()\n```\n\n::: {.cell-output-display}\n![Mean f0 by gender and attitude.](ch-regression-cat-cat_files/figure-pdf/fig-polite-f0-gend-att-1.pdf){#fig-polite-f0-gend-att fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nWe can improve the plot by \"dodging\" the jitter for informal and polite attitude with the `position` argument in `geom_jitter()`.\nThe argument takes one of the position functions: here we want `position_jitterdodge()`, used to dodge the jitter geometry.\nThe `dodge.width` argument sets how far apart the jitters should be (the width of the dodging).\n@fig-polite-f0-gend-att-2 is clearer, now that the jitters are dodged.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npolite_filt |> \n  ggplot(aes(gender, f0mn, colour = attitude)) +\n  geom_jitter(position = position_jitterdodge(dodge.width = 1))\n```\n\n::: {.cell-output-display}\n![Mean f0 by gender and attitude (repr).](ch-regression-cat-cat_files/figure-pdf/fig-polite-f0-gend-att-2-1.pdf){#fig-polite-f0-gend-att-2 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n::: callout-warning\n### Exercise 1\n\nTry out the `jitter.width` argument of `position_jitterdodge()`.\nSet it so that there is greater visual separation between the informal and polite jitters.\n:::\n\n## Fitting the model\n\nWe can now move onto fitting a regression model to `f0mn`, with `gender` and `attitude` as two categorical predictors.\nHere is what the model formula would look like:\n\n$$\\begin{aligned}\nf0mn_i & \\sim Gaussian(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot gen_{\\text{M}[i]} + \\beta_2 \\cdot att_{\\text{POL}[i]}\n\\end{aligned}$$\n\nThe formula has two indicator variables: $gen_{\\text{M}}$ and $att_{\\text{POL}}$.\nThe first variable states if the $f0mn$ value is from a female participant ($gen_{\\text{M}} = 0$) or a male participant ($gen_{\\text{M}} = 1$).\nThe second variable states if the $f0mn$ value is from the informal condition ($att_{\\text{POL}} = 0$) or the polite condition ($att_{\\text{POL}} = 1$).\n@tbl-gen-att-contrasts shows the treatment contrasts table.\n\n::: {#tbl-gen-att-contrasts}\n|                                            | $gen_\\text{M}$ | $att_\\text{POL}$ |\n|:------------------------------------------:|:--------------:|:----------------:|\n| `gender` = `F` and `attitude` = `informal` |       0        |        0         |\n|  `gender` = `F` and `attitude` = `polite`  |       0        |        1         |\n| `gender` = `M` and `attitude` = `informal` |       1        |        0         |\n|  `gender` = `M` and `attitude` = `polite`  |       1        |        1         |\n\n: Treatment contrasts coding of the categorical predictors gender and attitude.\n:::\n\n::: callout-warning\n### Exercise 2\n\nWork out the mathematical formula for $\\mu$ depending on each value combination of `gender` and `attitude`.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nJust plug in the `0` and `1` in the formula depending on the value of gender and attitude.\nYou want four formulae (one per gender/attitude combination).\n:::\n\nFitting a regression model with multiple predictors is as easy as just adding the predictors in the formula using a `+`: `f0mn ~ gender + attitude`.\nNote that we won't include the `1 +` for the intercept, since it's implicit, but you can still write it out if you wish.\nThe rest of the code has no surprises.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm <- brm(\n  f0mn ~ gender + attitude,\n  family = gaussian,\n  data = polite,\n  cores = 4,\n  seed = 7123,\n  file = \"cache/ch-regression-cat-cat_f0_bm\"\n)\n```\n:::\n\n\n## Interpreting models with multiple categorical predictors\n\nLet's print out the model summary.\nIf you look at the `Regression Coefficients` table, you will find three coefficients, each matching one of the $\\beta$ coefficients in the $\\mu$ formula above.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(f0_bm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: f0mn ~ gender + attitude \n   Data: polite (Number of observations: 212) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     255.14      4.48   246.47   263.81 1.00     4323     3184\ngenderM      -116.07      5.28  -126.30  -105.67 1.00     4618     2936\nattitudepol   -14.71      5.34   -25.05    -4.40 1.00     4708     2884\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    39.03      1.93    35.48    42.98 1.00     4604     2932\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n- `Intercept` is $\\beta_0$: this is the mean `f0mn` when `gender` = `F` and `attitude` = `informal`.\n\n- `genderM` is $\\beta_1$: this is the *difference* in mean `f0mn` between `gender` = `M` and `gender` = `F`, while controlling for `attitude`.\n\n- `attitudepol` is $\\beta_2$: this is the *difference* in mean `f0mn` between `attitude` = `polite` and `attitude` = `informal`, while controlling for `gender`.\n\nThe interpretation of the `Intercept` is straightforward, but you should note the \"while controlling for\" part in the other two coefficients.\nWhen we say that the model controls for attitude, we mean that the estimated difference between genders is adjusted for the fact that speakers also differ in the type of speech they produced (polite and informal).\nThe model accounts for the variation associated with attitude separately from the variation associated with gender.\nThe difference between genders is estimated by comparing males and females when producing the same type of speech.\nIn other words, the model asks: how different is the mean f0 of males compared with females when attitude is held constant?\nBecause both genders produced both polite and informal speech, the model can make this comparison separately for informal speech and for polite speech, and then combine these comparisons into a single estimate of the gender difference.\nThe same logic applies to attitude: the difference associated with attitude is estimated by comparing polite and informal speech while holding gender constant.\nThe model asks: how different is the mean f0 in polite speech compared with informal speech, after accounting for differences between genders?\n\nAnother way to understand what \"controlling for\" means is that the model combines the comparisons made at each level of the other predictor into a single estimate.\nFor example, the gender difference while controlling for attitude is based on the difference between males and females in informal speech and the difference between males and females in polite speech.\nThe coefficient for gender $\\beta_1$ is a weighted average of these two differences, where the weights depend on the structure of the data.\nIn a balanced design, where there are equal numbers of observations in each condition, this weighted average gives equal importance to each comparison.\nSimilarly, the attitude difference $\\beta_2$ while controlling for gender is a weighted average of the difference between polite and informal speech for males and the difference between polite and informal speech for females.\nThus, a regression coefficient with multiple predictors can be understood as an adjusted difference: it combines comparisons made while keeping the other predictors constant into a single estimate.\n\nHere is how we interpret the results of this model (based on the 95% CrIs):\n\n- `Intercept`: the mean `f0mn` with female participants in the informal condition (the reference levels) is between 246 and 264 Hz at 95% confidence.\n\n- `genderM`: the mean `f0mn` is between 106 and 126 Hz lower in male participants than female participants (when controlling for attitude), at 95% confidence.\n\n- `attitudepol`: the mean `f0mn` is between 4 and 25 Hz lower in the polite condition than in the informal condition (when controlling for gender), at 95% probability.\n\nIt is worth stressing here that, because of the \"averaging across levels\" of the \"other\" predictor, the estimated difference of each predictor is implied to be the same in all levels of the other predictor.\nWe can see this by plotting the expected `f0mn` based on both predictors.\nWe use `conditional_effects()` here for convenience (you will have to plot the posterior distributions from the draws in the exercise below).\nFirst, @fig-f0-bm-cond shows the expected values of `f0mn` depending on gender and attitude, separately.\n\n\n::: {#fig-f0-bm-cond .cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nconditional_effects(f0_bm, \"gender\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n* fill : \"NA\"\n* colour : \"NA\"\nIgnoring unknown labels:\n* fill : \"NA\"\n* colour : \"NA\"\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nconditional_effects(f0_bm, \"attitude\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n* fill : \"NA\"\n* colour : \"NA\"\nIgnoring unknown labels:\n* fill : \"NA\"\n* colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Expected predictions of mean f0 by gender.](ch-regression-cat-cat_files/figure-pdf/fig-f0-bm-cond-1.pdf){#fig-f0-bm-cond-1 fig-align='center'}\n:::\n\n::: {.cell-output-display}\n![Expected predictions of mean f0 by attitude.](ch-regression-cat-cat_files/figure-pdf/fig-f0-bm-cond-2.pdf){#fig-f0-bm-cond-2 fig-align='center'}\n:::\n\nExpected predictions of mean f0 by gender and by attitude.\n:::\n\n\nTo obtain a single plot that shows the expected `f0mn` for gender and attitude together, you can specify both predictors separated by a colon `gender:attitude`.\nThe code below produces @fig-f0-bm-cond-both.\nThe order you put the predictors in matters: with `gender:attitude`, gender is places on the *x*-axis and attitude is included as a colour aesthetic.\nDeciding which order to use depends on the data and question: here it makes sense to use `gender:attitude` since our main question is about attitude.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconditional_effects(f0_bm, \"gender:attitude\")\n```\n\n::: {.cell-output-display}\n![Expected predictions of mean f0 by gender and attitude.](ch-regression-cat-cat_files/figure-pdf/fig-f0-bm-cond-both-1.pdf){#fig-f0-bm-cond-both fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n@fig-f0-bm-cond-both should make you appreciate why the effect of attitude is modelled to be the same in female and male participants (and conversely, the effect of gender is the same in informal and polite attitude; you can see this by plotting with the order `attitude:gender`).\nIf you compare the dots for informal/polite within each gender in the plot, you will notice that the distance between them is basically the same in both genders.\n\n::: callout-warning\n### Exercise 3\n\nUse `as_draws_df()` to obtain the model's draws and recreate the following plot.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](ch-regression-cat-cat_files/figure-pdf/exercise-3-1.pdf){fig-align='center'}\n:::\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n- You need `mutate()` to create new columns with the expected draws for each gender/attitude combination.\n\n- Then you can pivot the new columns so that you get two columns: one which states the gender/attitude combination and one that holds the calculated expected draw.\n\n- You can then plot the pivoted data.\n\n- Alternatively, you can use `epred_draws()` from tidybayes and plot the resulting draws.\n:::\n\nThe fact that the model is estimating the coefficients for gender and attitude independently from each other begs the question: what if the effect of attitude is *not* the same in both genders?\nBased on the data, shown again in @fig-polite-f0-gend-att-repr, it seems that the male data does not show much of a difference depending on attitude, as the female data does.\n\n\n::: {.cell layout-align=\"center\" fig-label='Mean f0 by gender and attitude (repr).'}\n\n```{.r .cell-code  code-fold=\"true\"}\npolite_filt |> \n  ggplot(aes(gender, f0mn, colour = attitude)) +\n  geom_jitter(alpha = 0.7, position = position_jitterdodge(jitter.width = 0.1, seed = 2836))\n```\n\n::: {.cell-output-display}\n![](ch-regression-cat-cat_files/figure-pdf/fig-polite-f0-gend-att-repr-1.pdf){#fig-polite-f0-gend-att-repr fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nHow do we let the model estimate a different effect of attitude based on gender?\nThis is the topic of the next chapter.\n",
    "supporting": [
      "ch-regression-cat-cat_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}