{
  "hash": "639e30db1f80302d563e954b7f13dff9",
  "result": {
    "engine": "knitr",
    "markdown": "# Interactions in regression: two categorical predictors {#sec-regression-interaction}\n\n![](/img/badge-stats.png) ![](/img/badge-r.png)\n\nThe previous chapter explained how to include two predictors in a regression model and how to interpret the results of the model.\nBut we were left wondering: what if the effect of attitude differs between the two genders?\nIn this chapter we will talk about **interactions**: regression models can estimate different effects of one predictor depending on the levels of the other other predictor, by adding a so-called *interaction term*.\nKeep reading to learn about them.\n\n## Is the effect of attitude modulated by gender?\n\n\n\nLet's start by attaching the packages and then reading and filtering the `polite` data [@winter2012].\nWe drop `NA` values from the `f0mn` column.\n\n``` r\nlibrary(tidyverse)\ntheme_set(theme_light())\nlibrary(brms)\nlibrary(tidybayes)\nlibrary(posterior)\nlibrary(ggdist)\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npolite <- read_csv(\"data/winter2012/polite.csv\")\n\npolite_filt <- polite |> \n  drop_na(f0mn)\n```\n:::\n\n\n@fig-polite-f0-gend-att-repr-2 shows once again the mean f0 values split by gender and attitude.\nIn principle, we have no reason to expect that the effect of attitude will be the same in both genders, and conversely we have no reason to expect the opposite (that it will be different).\nThe best way to address this in regression modelling is to allow the model to estimate the (possible) difference.\nA common misconception in the traditional way of running regression models is that if an interaction term indicates that there is no interaction, then it is fine to drop the interaction term from the model.\nHowever, you can only estimate the interaction by including it in the model and after you do that there is no reason to run a new model without it if you believe there is no interaction.\nSo my general suggestion is to include interactions terms if you think it makes sense to expect an interaction, even if just in theory.\n\n\n::: {.cell layout-align=\"center\" fig-label='Mean f0 by gender and attitude (repr).'}\n\n```{.r .cell-code  code-fold=\"true\"}\npolite_filt |> \n  ggplot(aes(gender, f0mn, colour = attitude)) +\n  geom_jitter(alpha = 0.7, position = position_jitterdodge(jitter.width = 0.1, seed = 2836))\n```\n\n::: {.cell-output-display}\n![](ch-regression-interaction_files/figure-pdf/fig-polite-f0-gend-att-repr-2-1.pdf){#fig-polite-f0-gend-att-repr-2 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n## Interaction terms\n\nTo allow a regression model to estimate \"interactions\" between predictors, or in other words to estimate different effects of one predictors based on the levels of the other, we need to include so-called **interaction terms**.\nAn interaction term, is a model term that tells the model to estimate interactions.\nBefore we see how to include interaction terms in R/brms, let's go through the model's formula.\n\nWe will model mean f0 `f0mn` as a function of `gender` and `attitude` and an interaction between the two.\nHere is what the formula looks like:\n\n$$\\begin{aligned}\nf0mn_i & \\sim Gaussian(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\quad \\beta_0 \\\\\n & \\quad + \\beta_1 \\cdot gen_{\\text{M}[i]} \\\\\n & \\quad + \\beta_2 \\cdot att_{\\text{POL}[i]} \\\\\n & \\quad + \\beta_3 \\cdot gen_{\\text{M}[i]} \\cdot att_{\\text{POL}[i]}\n\\end{aligned}$$\n\nThere are now not just three $\\beta$ coefficients, but four: $\\beta_0, \\beta_1, \\beta_2, \\beta_3$.\nThe new coefficient that we haven't seen before is $\\beta_3$.\nThis is the coefficient of the interaction term of gender and attitude.\nIt is common to refer to the coefficients $\\beta_1$ and $\\beta_2$ as the coefficients of the **main effects** of gender and attitude respectively, and to $\\beta_3$ as the coefficient of the **interaction** between gender and attitude.\nLet's work out the formula of $\\mu$ depending on the combinations gender and attitude: remember that $gen_\\text{M}$ is 0 for female and 1 for male, and $att_\\text{POL}$ is 0 for informal and 1 for polite.\n\n|                     |                                         |\n|---------------------|-----------------------------------------|\n| female and informal | $\\beta_0$                               |\n| male and informal   | $\\beta_0 + \\beta_1$                     |\n| female and polite   | $\\beta_0 + \\beta_2$                     |\n| male and polite     | $\\beta_0 + \\beta_1 + \\beta_2 + \\beta_3$ |\n\nWe get this because when either $gen_\\text{M}$ or $att_\\text{POL}$ are 0, the corresponding $\\beta$ coefficient gets dropped from the equation.\nImportantly, notice how for male/polite we need all four coefficients.\nFor male and polite mean f0, we need the coefficient for male $\\beta_1$ and that for polite $\\beta_2$, but also the interaction coefficient $\\beta_3$ because in this combination $gen_\\text{M}$ and $att_\\text{POL}$ are both 1.\nYou can think of $\\beta_3$ as the \"adjustment\" to the individual effects of gender = male and attitude = polite.\nIn other words, the interaction coefficient $\\beta_3$ tells you how the combined effects of gender = male and attitude = polite differ from their simple sum (i.e. $\\beta_1 + \\beta_2$).\n\n::: callout-warning\n## Exercise 1\n\nGo to [Regression Models Illustrated](https://stefanocoretta.shinyapps.io/lines/) and play with the \"Categorical + Categorical\" tab.\n:::\n\nMoving on to R, we can include an interaction term between `gender` and `attitude` in the R formula with `gender:attitude` (the two predictors separated by a colon `:`).\nSimilarly to how we refer to the coefficients in a model with interactions, we call the `gender` and `attitude` terms in the R formula the **main terms** and `gender:attitude` as the **interaction term**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int <- brm(\n  f0mn ~ gender + attitude + gender:attitude,\n  family = gaussian,\n  data = polite,\n  cores = 4,\n  seed = 7123,\n  file = \"cache/ch-regression-interaction_f0_bm_int\"\n)\n```\n:::\n\n\nNote that there is a [syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar) for interactions: instead of writing in full `gender + attitude + gender:attitude` you can just write `gender * attitude` (the two predictors separated by a star `*`).\nThe \"star\" syntax expands to the full syntax under the hood when the model is run.\nIt is up to you which syntax you use, although for beginners I suggest using the longer one for clarity.\nGetting a regression model to estimate interactions is easy, but a warning: because we have included an interaction in the model, the interpretation of the coefficients has changed slightly relative to how we interpret the coefficients of categorical predictors in models without interactions!\n\n::: callout-tip\n## Interactions\n\n![](img/interactions.png){fig-align=\"center\" width=\"500\"}\n\nAn **interaction term** allows the effect of one predictor to vary depending on the value of the other predictor.\n\nA model with an interaction has **main terms** and an **interaction term**.\nThe coefficients of the main terms are the **coefficients of the main effects** while the coefficient of the interaction term is the **interaction coefficient**.\n:::\n\n## Interpreting models with interactions\n\nLet's look at the model summary.\nWith interactions, the coefficients of categorical predictors are interpreted slightly differently than when there are no interactions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(f0_bm_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: f0mn ~ gender + attitude + gender:attitude \n   Data: polite (Number of observations: 212) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept             256.56      5.20   246.38   267.27 1.00     2632     2950\ngenderM              -119.38      7.66  -134.08  -104.50 1.00     2532     2665\nattitudepol           -17.48      7.28   -31.76    -3.18 1.00     2573     2806\ngenderM:attitudepol     6.65     10.67   -14.20    27.47 1.00     2191     2693\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    39.10      1.94    35.52    43.14 1.00     3834     2779\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n- `Intercept` is $\\beta_0$: this is, as you would expect, the mean f0 when gender and attitude are at their reference levels, i.e. female and informal.\n  According to the model, there is a 95% probability that the mean f0 is between 246 and 267 Hz with female speakers and informal attitude.\n\n- `genderM` is $\\beta_1$, the coefficient of the main effect of gender: this is the difference in mean f0 between male and female gender, *when attitude is informal* (i.e. at the reference level of attitude).\n  This differs from the interpretation in models with no interactions where instead the coefficient would capture the *average* difference between male and female gender.\n  According to the model, the mean f0 is 105 to 134 Hz lower in male than in female participants, when the attitude is informal.\n\n- `attitudepol` is $\\beta_2$, the coefficient of the main effect of attitude: this is the difference in mean f0 between polite and informal attitude, *when gender is female* (i.e. at the reference level of gender).\n  This also differs from the interpretation in models with no interactions where instead the coefficient would capture the *average* difference between polite and informal attitude.\n  According to the model, the mean f0 is 3 to 32 Hz lower in polite than in informal speech, in female speakers.\n\n- `genderM:attitudepol` is $\\beta_3$: this is the interaction coefficient.\n  This coefficient tells you the *adjustment* you have to make to the effects of gender and attitude (so $\\beta_1 +\\beta_2 + \\beta_3$), on top of what is predicted by the additive effects of gender and attitude (so $\\beta_1 + \\beta_2$).\n  According to the model, the difference between female informal and male polite speech differs from the additive effect of gender and attitude by -14 to +27 Hz, at 95% confidence.\n  The 95% CrI \\[-14, +27\\] spans both negative and positive values: there is uncertainty as to whether the effect of attitude differs in the two genders (and, symmetrically, whether the effect of gender differs in informal and polite speech), and as to weather the difference is positive or negative.\n  The interval might indicate that a positive difference is more likely, given that the interval spans a wider range of positive values than negative values.\n\nLet's extract the model's draws and process them to get summary measures and relevant plots.\n\n## Model's draws and expected values\n\nWe can extract the draws from the model object as usual.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_draws <- as_draws_df(f0_bm_int)\n```\n:::\n\n\nTo calculate the expected values of f0, we plug in the columns from the draws object `f0_bm_int_draws` according to the model's formula.\nTo name the new columns with the expected predictions, we use `F` for female and `M` for male for gender, and `inf` for informal and `pol` for polite for attitude.\nNote that, since the name of interaction coefficient `b_genderM:attitudepol` contains a colon `:`, we need to surround it with back-ticks to prevent R for interpreting the colon `:` as the range operator (like in `1:5`, which returns integers from 1 to 5).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_draws <- f0_bm_int_draws |> \n  mutate(\n    # \\beta_0\n    F_inf = b_Intercept,\n    # \\beta_0 + \\beta_1\n    F_pol = b_Intercept + b_attitudepol,\n    # \\beta_0 + \\beta_2\n    M_inf = b_Intercept + b_genderM,\n    # \\beta_0 + \\beta_1 + \\beta_2 + \\beta_3\n    M_pol = b_Intercept + b_genderM + b_attitudepol + `b_genderM:attitudepol`\n  )\n```\n:::\n\n\nLet's plot the distributions of the expected values we just calculated.\nWe need to pivot the draws object: to make plotting easier, we need a column with the gender value and one column with the attitude value, and also a column with the expected values.\nWe can split the `cond` column with `separate()` from dplyr.\nThis function splits strings by punctuation characters, like `_`, so it works with strings like `F_inf`, which gets split into `F` and `inf`.\nThe two new values are input into the specified new columns `gender` and `attitude` (the user picks and specifies the column names as one of the arguments).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_epred <- f0_bm_int_draws |> \n  # First, select only the columns we need to pivot\n  select(F_inf:M_pol) |> \n  # From wide to long\n  pivot_longer(F_inf:M_pol, names_to = \"cond\", values_to = \"epred\") |> \n  # Split `cond` column to make a gender and an attitude column\n  separate(cond, c(\"gender\", \"attitude\"))\n\nf0_bm_int_epred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16,000 x 3\n   gender attitude epred\n   <chr>  <chr>    <dbl>\n 1 F      inf       258.\n 2 F      pol       232.\n 3 M      inf       134.\n 4 M      pol       128.\n 5 F      inf       252.\n 6 F      pol       245.\n 7 M      inf       133.\n 8 M      pol       116.\n 9 F      inf       249.\n10 F      pol       234.\n# i 15,990 more rows\n```\n\n\n:::\n:::\n\n\nThere is also a swifter way to calculate expected values, which we encountered previously: using the `epred_draws()` function from tidybayes.\nI recommend that you practice calculating the expected values manually as we have done above, because it makes it explicit how the expected values derive from the model coefficients.\nLet's use `epred_draws()` now.\n\nThe first step is to create a prediction grid.\nInstead of writing down the combinations of gender and attitude by hand, we can use `expand_grid()` from tidyr.\nThe function takes a name-value pairs.\nThe names correspond to the column names in the resulting tibble.\nThis tibble will have one row for each combination of the values in the name-value pairs.\nSee the output of the code below.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nepred_grid <- expand_grid(\n  gender = c(\"F\", \"M\"),\n  attitude = c(\"inf\", \"pol\")\n)\nepred_grid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 2\n  gender attitude\n  <chr>  <chr>   \n1 F      inf     \n2 F      pol     \n3 M      inf     \n4 M      pol     \n```\n\n\n:::\n:::\n\n\nNote that the prediction grid must use *exactly* the same variable and value names as the ones of the data used in the model.\nOur prediction grid now has two columns, `gender` and `attitude`, and four rows, one for each combination of gender and attitude.\nWhen your predictors have many levels, it would be tedious to write down the combinations yourself and `expand_grid()` makes a useful shortcut.\n\nWith the prediction grid, we can now obtain the posterior draws of the expected values using `epred_draws()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_epred_2 <- epred_draws(\n  f0_bm_int,\n  epred_grid\n)\nf0_bm_int_epred_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16,000 x 7\n# Groups:   gender, attitude, .row [4]\n   gender attitude  .row .chain .iteration .draw .epred\n   <chr>  <chr>    <int>  <int>      <int> <int>  <dbl>\n 1 F      inf          1     NA         NA     1   258.\n 2 F      inf          1     NA         NA     2   252.\n 3 F      inf          1     NA         NA     3   249.\n 4 F      inf          1     NA         NA     4   253.\n 5 F      inf          1     NA         NA     5   258.\n 6 F      inf          1     NA         NA     6   252.\n 7 F      inf          1     NA         NA     7   261.\n 8 F      inf          1     NA         NA     8   261.\n 9 F      inf          1     NA         NA     9   256.\n10 F      inf          1     NA         NA    10   260.\n# i 15,990 more rows\n```\n\n\n:::\n:::\n\n\nSomething that makes this method convenient is that the resulting tibble is already \"longer\" so there is no need to pivot it for plotting.\n\nNow we can plot the expected values with ggplot2 (@fig-f0-bm-int-epred).\nWe set `scales = \"free_x\"` in `facet_grid()` to allow ggplot to use different scales in the *x*-axis (try to run the code without specifying the `scales` argument to see why).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_epred_2 |> \n  ggplot(aes(.epred, attitude)) +\n  stat_halfeye() +\n  facet_grid(cols = vars(gender), scales = \"free_x\") +\n  labs(x = \"Mean f0 (Hz)\")\n```\n\n::: {.cell-output-display}\n![Density plot of the expected values of mean f0 by gender and attitude.](ch-regression-interaction_files/figure-pdf/fig-f0-bm-int-epred-1.pdf){#fig-f0-bm-int-epred fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nAn alternative to `stat_halfeye()` is `stat_interval()`.\nBy default, it plots the 50-80-95% CrIs.\n@fig-f0-bm-int-epred-interval shows the CrIs of the expected values of mean f0.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_epred_2 |> \n  ggplot(aes(attitude, .epred)) +\n  stat_interval() +\n  facet_grid(cols = vars(gender))\n```\n\n::: {.cell-output-display}\n![Intervals plot of the expected values of mean f0 by gender and attitude.](ch-regression-interaction_files/figure-pdf/fig-f0-bm-int-epred-interval-1.pdf){#fig-f0-bm-int-epred-interval fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nWe can observe two main things:\n\n- The f0 of female participants is generally higher than that of male participants.\n\n- In both genders, f0 is somewhat higher in informal than in polite speech.\n\n- Possibly, the attitude difference is somewhat larger in female than in male participants.\n\nThese general observations can be quantified using CrIs from the model.\nFor example, let's take the attitude difference in male speakers.\nWe can compute the posterior draws of this difference from the expected values in `f0_bm_int_draws` and take summary measures.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_draws |> \n  mutate(\n    M_pol_inf = M_pol - M_inf\n  ) |> \n  summarise(\n    mean_diff = mean(M_pol_inf), sd_diff = sd(M_pol_inf),\n    lo_diff = quantile2(M_pol_inf, probs = 0.025),\n    hi_diff = quantile2(M_pol_inf, probs = 0.975)\n  ) |>\n  round()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 4\n  mean_diff sd_diff lo_diff hi_diff\n      <dbl>   <dbl>   <dbl>   <dbl>\n1       -11       8     -27       5\n```\n\n\n:::\n:::\n\n\nThe mean difference in polite vs informal speech in male speakers is -11 Hz (SD = 8) and the 95% CrI is \\[-27, +5\\] Hz.\nThis is somewhat indicative of a difference (polite speech is produced with a somewhat lower f0) but it is also possible that there is instead a smaller positive difference (+5 Hz).\nComparing this with the effect of attitude in female participants (as given by $\\beta_2$ or `attitudepol`) which is at 95% confidence between -32 to -3 Hz, we cannot really argue for or against the effect of attitude being different in the two genders.\nIn other words, we are left with a certain level of uncertainty.\n\nThe $\\beta_3$ coefficient estimates the difference in the difference of attitude in males vs female participants, so we can estimate the uncertainty of the difference by calculating CrIs of the coefficient.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf0_bm_int_draws |> \n  summarise(\n    mean = mean(`b_genderM:attitudepol`) |> round(),\n    sd = sd(`b_genderM:attitudepol`) |> round(),\n    `95%` = paste0(\"[\", paste(quantile2(`b_genderM:attitudepol`, c(0.025, 0.975)) |> round(), collapse = \", \"), \"]\"),\n    `80%` = paste0(\"[\", paste(quantile2(`b_genderM:attitudepol`, c(0.1, 0.9)) |> round(), collapse = \", \"), \"]\"),\n    `70%` = paste0(\"[\", paste(quantile2(`b_genderM:attitudepol`, c(0.15, 0.85)) |> round(), collapse = \", \"), \"]\"),\n    `60%` = paste0(\"[\", paste(quantile2(`b_genderM:attitudepol`, c(0.2, 0.8)) |> round(), collapse = \", \"), \"]\"),\n    `50%` = paste0(\"[\", paste(quantile2(`b_genderM:attitudepol`, c(0.25, 0.75)) |> round(), collapse = \", \"), \"]\")\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 7\n   mean    sd `95%`     `80%`    `70%`    `60%`    `50%`   \n  <dbl> <dbl> <chr>     <chr>    <chr>    <chr>    <chr>   \n1     7    11 [-14, 27] [-7, 20] [-4, 18] [-2, 16] [-1, 14]\n```\n\n\n:::\n:::\n\n\nAt 95% probability, given the 95% CrI of \\[-14, +27\\], the difference between attitudes in males is between 14 Hz lower and 27 Hz higher than the corresponding difference in females (the 95% CrI of which is \\[-32, -3\\]).\nAt 60% probability, the difference in males is between 2 Hz lower and 16 Hz higher (95% CrI \\[-2, +15\\]) than that in females.\nWhile we can be quite confident that polite speech has a somewhat lower mean f0 in females, this might be the case in male speakers too although possibly to a lower degree and considering there might be no difference by attitude in males.\nWe are just very uncertain about it.\n\n## Reporting\n\nThe following paragraph shows you how to report the model specification of the model we fitted in this chapter.\nI don't include the part where you report the results of the model, because it would just be repeating the text from the previous sections.\n\n> We fitted a Bayesian regression model using the brms package [@burkner2017] in R [@rcoreteam2025].\n> We used a Gaussian distribution for the outcome variable, mean f0 (in Hz).\n> We included attitude (informal vs polite) and gender (female vs male) as the regression predictors and their interaction.\n> Both predictors were coded using the default R treatment contrasts, with informal and female set as the reference levels.\n\nNote that there isn't a single \"right\" way of reporting model results, or a fixed procedure.\nIt much depends on the specific research question and on which part of the results you place focus on.\nGenerally speaking, you should report credible intervals at various levels of probability, mean and SD and include plots (density or interval plots) of regression coefficients, expected values, and of other comparisons (not already covered by the regression coefficients).\nWith more complex models, including all that in a report might be too much so you can take advantage of tables and appendices: for example, you can refer the reader to a table containing summaries of the regression coefficients and only directly report relevant CrIs in the text, accompanied by some plots of relevant posterior distributions.\n\n## Summary\n\n::: {.callout-note appearance=\"minimal\"}\n- Interaction terms allow us to estimate how the effect of one predictor differs based on the levels of another.\n\n- Interpretation of a coefficient for any one predictor is thus based on the reference level of the other predictors.\n\n- We can still calculate expected predictions and any comparison of interest based on the model's draws.\n:::\n",
    "supporting": [
      "ch-regression-interaction_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}